// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://foyupblfyldvjmvmlbkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZveXVwYmxmeWxkdmptdm1sYmtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjIwMTksImV4cCI6MjA3MzA5ODAxOX0.i8aO09Ljsz0UClCzT6WSh7ru0BGqnlZ5PpMVni7LQ-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});